greduan/emacs-theme-gruvbox

gruvbox-theme.el

Hi, I personally don't use helm, but this is causing an error when loading the theme in Emacs. Great theme btw. :-)

Fix color name typo in helm support

---

gruvbox-theme.el

Contrieved example follows to show the effect

Adds popup-tip-face colors to look nice with flycheck-pos-tip.

---

gruvbox-theme.el

Here's a couple of examples, tried to make it look like ido in general
When there's more matches
When there's only one match

Adds support for company-mode.

---

gruvbox-theme.el

I added support for smart-mode-line. To make it look good I had to change the mode-line colors. The colors match the ones currently being used for the Helm action bar.
Any feedback is appreciated.
I hope you like it!

Add support for smart-mode-line

---

gruvbox-theme.el

Hi, I fixed the line number being highlighed when the cursor is over a paren on the first column like this

Fixed line number being highlighed with parens

---

gruvbox-theme.el

Currently font-lock-string-face is set to green, which is already being used by font-lock-function-name-face. I think we should use yellow instead, which is currently not being used in font-lock definitions.
What do you think?
Cheers!

Change font-lock-function-name-face to yellow

---

gruvbox-theme.el

The original Vim theme allowed setting the background colour for one of three different 'contrast' options: soft, medium, and hard.
This patch allows setting a `gruvbox-contrast` variable to control which background colour the theme uses, e.g.
```elisp
(setq gruvbox-contrast 'soft)
```
for the soft variant.

Add preliminary support for setting the contrast

---

gruvbox-theme.el

This commit adds a somewhat opinionated theme for `message-mode` buffers, intending to match other buffers instead of the default theme.
Before (default colours):
After:

Add support for message-mode

---

gruvbox-theme.el

Before (default colours):
After:
Generally followed the semantics of `font-lock-mode` on this one.

Add support for elfeed-mode

---

README.md
gruvbox-theme.el

isearch currently uses default colors from emacs,  these changes try to replicate vim-gruvbox theme for vim-search (isearch and lazy-matching
also added isearch fail with gruvbox-bright_red background
complete other Anzu faces

Adding isearch specific colors

---

gruvbox-theme.el

show-pren is built-in parenthesis matching mechanism for emacs which
only hasa two faces, show-paren-match and show-paren-mismatch
I used gruvbox-dark3 for show-paren-match to replecate the default
behavior of vim-gruvbox in MatchParen variable.
A bright red back ground used to show mismatched parenthesis.

Adding two show-pren specific colors

---

gruvbox-theme.el

ace-jump-mode is one of the frequently used packages to jump to a head
character in current buffer, though it's being replaced by newer
avy-mode, but it still is being used widely
https://github.com/winterTTr/ace-jump-mode
ace-window is a package for selecting a window to switch to, a bright
orange foreground in a box with height ratio of 4 is used to indicate
window numbers in ace-window mode
https://github.com/abo-abo/ace-window

 Adding ace-jump and ace-window specific faces

---

gruvbox-theme.el

All changes are pretty much straight from the darktooth emacs
theme (https://github.com/emacsfodder/emacs-theme-darktooth).  Their
choices fit pretty well and look much better than dired+'s defaults.

Preliminary dired+ support.

---

gruvbox-theme.el

I just added faces for headers in markdown-mode, with the same colors as those in org-mode.
Thanks a lot for this theme, which I find really beautiful and usable.

Add headers colors for markdown-mode

---

gruvbox-theme.el

This will customize the face exposed by the ```hlinum``` package. The result will look like this:
Basically it provides the same face settings as the standard line highlight to the currently selected line number.
Thanks!

added support for 'linum-highlight-face'

---

gruvbox.el

Fix for https://github.com/greduan/emacs-theme-gruvbox/issues/68
Now using the opposite of the background color instead of white

Avy face fix

---

gruvbox.el

This fixes an issue with popup menu entries overlapped faces with an underline
This is what happens in the current version of gruvbox when using the auto-complete package
This is what it looks like after this patch

Explicitly disabled underline for popup faces

---

.gitignore
gruvbox.el

In my initial pull request I added box around ace-jump and ace-window letters, which at the time I thought was a good idea (it merged to the upstream), after using it for some times and seeing how it annoyingly changes the layout of whole text, now I think it's a good Idea to just see head letters in ace-jump without any boxes.
I also changed ace-window face to gruvbox-bright_red to be consistent with ace-window
and also added two line to .gitignore for Emacs backup files ~* & #*# for folks like myself who always clutter their working directory with those junks.

Removing box styles from ace-jump and ace-window faces

---

gruvbox.el

Default color was SaddleBrown which did not fit the pallete and was
hard to read on a dark background

Added org-latex-and-related face

---

gruvbox.el

I added some faces to company, where company-preview was using default blue like this
After change it uses lightblue4 as background and light0 as foreground
After change in dark theme
After change in light theme
Also company previews were using default yellow like this:
I changed background to neutral_yellow and foreground to gruvbox-black
dark theme
light theme
Also tooltips had no theme

Add some faces to company-mode and Theme tooltips

---

gruvbox.el

Left side of screen in emacs running in a 256-color terminal, right side is GUI emacs.
Dark Theme
Light theme

Added widget faces

---

gruvbox.el

Fix for https://github.com/greduan/emacs-theme-gruvbox/issues/83
Linum faces now inherit from the native line number faces

Updated linum faces and added suport for native line numbers

---

gruvbox.el

Colors were chosen to match the gruvbox pallete while still being
similar to their unthemed colors.
Screenshots of changes below
Dark theme:
Light them:

Added support for sh-quoted-exec and sh-heredoc

---

gruvbox-dark-hard-theme.el
gruvbox-dark-medium-theme.el
gruvbox-dark-soft-theme.el
gruvbox-light-hard-theme.el
gruvbox-light-medium-theme.el
gruvbox-light-soft-theme.el
gruvbox-theme.el
gruvbox.el

In commit https://github.com/greduan/emacs-theme-gruvbox/commit/b6d93d25faff573a7f7712bc33fce1fe422473e0 an issue was fixed with loading the faces for eshell. 
Unfortunately with this commit all (inheriting) eshell faces now look the same (White on black for dark themes, black on white for light themes).
This fixed that by defining specific colors instead of relying on inheritance.

Fixed issue with eshell faces not being recognized

---

gruvbox-dark-hard-theme.el
gruvbox-dark-medium-theme.el
gruvbox-dark-soft-theme.el
gruvbox-light-hard-theme.el
gruvbox-light-medium-theme.el
gruvbox-light-soft-theme.el
gruvbox-theme.el
gruvbox.el

This fixes the issues of https://github.com/greduan/emacs-theme-gruvbox/issues/108
Old contrast of the line numbers was a bit low, most noticeably on the dark-hard and light-hard variants of the theme.
The paren match face was far more subtle than other themes. It was easily visible with the default background but was hard to see when combine with hl-line-mode.
Screenshots of new faces (with line numbers and hl-line-mode enabled):
Screenshots with paren face mode (A mode I personally use which normally dims the parenthesis):

Increased visibility of matching parenthises and line numbers

---

gruvbox-dark-hard-theme.el
gruvbox-dark-medium-theme.el
gruvbox-dark-soft-theme.el
gruvbox-light-hard-theme.el
gruvbox-light-medium-theme.el
gruvbox-light-soft-theme.el
gruvbox-theme.el
gruvbox.el

In response to https://github.com/greduan/emacs-theme-gruvbox/issues/112
The func-mode face is changed from the default drab blue to the bright-blue in the gruvbox palletes.

Added support for which-function-mode

---

gruvbox-dark-hard-theme.el
gruvbox-dark-medium-theme.el
gruvbox-dark-soft-theme.el
gruvbox-light-hard-theme.el
gruvbox-light-medium-theme.el
gruvbox-light-soft-theme.el

The `pdf-tools` package has a `pdf-view-midnight-minor-mode` with bright text on dark background. Using `gruvbox` colors makes it look nicer.
The screenshots are here, however, other colors may be more beautiful.
`gruvbox-dark-soft`
`gruvbox-light-soft`

Support pdf-view-midnight-minor-mode

---

README.md
gruvbox-dark-hard-theme.el
gruvbox-dark-medium-theme.el
gruvbox-dark-soft-theme.el
gruvbox-light-hard-theme.el
gruvbox-light-medium-theme.el
gruvbox-light-soft-theme.el
gruvbox-theme.el
gruvbox.el

`auto-dim-other-buffers.el` is a minor mode that provides a visual
distinction between active and inactive buffers by modifying face
attributes. The source code for auto-dim-other-buffers.el is available
at https://github.com/mina86/auto-dim-other-buffers.el.
In order to implement support for `auto-dim-other-buffers.el` in the
gruvbox theme, this commit introduces, in addition to the `gruvbox-bg`
colour that contains the background colour under the current theme, a
secondary `gruvbox-bg_inactive` colour that is always one level
softer. In this way, `auto-dim-other-buffers.el` with gruvbox provides a
subtle indication of active and inactive buffers, where inactive
buffers have minimally lower contrast.
In addition, this commit harmonizes the colour definitions among the
soft, hard and …

Add support for auto-dim-other-buffers.el

---

README.md
gruvbox.el

Hi there! I've added faces for neotree, mostly inspired by the dired colors. I thought it appropriate since neotree is also displaying files and directories. Here are a couple of screenshots:
I didn't make all the variations since the automated screenshot facility is not working for me at the moment. Hopefully this two are enough, but if not let me know and I can take new ones when I have some time.

Add faces for neotree

---

gruvbox.el

Fixes an error for users that don't have neotree installed described by @aashiks in #132.
Fixes #133

Set attributes for neo-root-dir-face directly instead of inheriting

---

gruvbox.el

Hi! Here are some faces for [wgrep](https://github.com/mhayashi1120/Emacs-wgrep), another feature that I use rather frequently. Hopefully useful for others too. No weird inherits here, only one from builtin highlight face, so (hopefully) shouldn't break anything this time :-)
I didn't add it to the README, since it's more of a support feature for grep than a main feature, but I could add it if you think it's appropriate.
Screenshots:
Dark before apply:
Dark after apply
Light before apply:
Light after apply:

Add faces for wgrep

---

gruvbox.el

Hello :-)
The current color for the sml/global face (used for rendering e.g.
column indicator, minor mode names) is gruvbox-burlywood4. This color
doesn't invert and it's invisible in a focused window when using the
light hard variant.
Before:
After:
This PR fixes this by using gruvbox-light4, which will invert correctly
and display properly in light themes.

Make some smart-mode-line info visible in light theme

---

gruvbox.el

There is a native tab mode on the Emacs master branch now. This update provides some basic theming to keep the visuals in-step with other effects provided by the theme. The active tab is darker (in light modes) or lighter (in dark modes) than other tabs to indicate that it's active, while the rest of the tab line blends in with the background.

Add basic theming for tab bar mode

---

gruvbox-dark-hard-theme.el

It turns out neutral colors were not loaded in this theme, but they are now required by Gruvbox, with the new ERC compatibility code.
- `(erc-timestamp-face         (:foreground gruvbox-neutral_green))`
- `(erc-pal-face               (:foreground gruvbox-neutral_yellow :weight 'bold))`
This patch adds the neutral colors and resolves the error I reported earlier. The same idea may need to be replicated across other non-default themes.

add neutral tones to dark theme; fix #151

---

gruvbox-dark-hard-theme.el
gruvbox-dark-medium-theme.el
gruvbox-dark-soft-theme.el
gruvbox-light-hard-theme.el
gruvbox-light-medium-theme.el
gruvbox-light-soft-theme.el
gruvbox-theme.el

According to the documentation, the neutral and bright colors are almost identical.
- `gruvbox-neutral_orange` was missing in gruvbox-theme.el so I have created it as a copy of `gruvbox-bright_orange`.

gruvbox-neutral_orange was missing from gruvbox-theme.el; neutral colors missing more widely

---

gruvbox.el

I think in the current configuration the contrast for the matched items with the background is too low.  The fact that the minibuffer is usually also very small adds further to the poor legibility.
This change proposed the following:
- Show `ido-only-match` in bold bright green, which is the same as `success`.
- Show `ido-first-match` in the default foreground color with bold and underline.  This matches `ivy-current-match`.
- Show `ido-subdir` in the same color as `dired-directory`.
I think these changes make the ido faces more legible and also more consistent with the rest of the theme.

Improve legibility of ido faces

---

gruvbox.el

Most of the faces inherit from other modes, these don't.
Sorry i kinda rushed these, there might be better colors, the original one is bright yellow, so totally unreadable.

Add lsp mode coloring

---

gruvbox.el

this is a fix suggested in [this issue](https://github.com/greduan/emacs-theme-gruvbox/issues/176#issue-797638814). I looked at dark / light soft, medium and hard and it seems fine.

fix company-mode backgrounds for soft themes

---

README.md

Hi!
We have now added this package to [NonGNU ELPA](http://elpa.nongnu.org/nongnu/gruvbox-theme.html) (see link), a new Emacs Lisp package archive that will be enabled by default in Emacs 28. This means that users of that version or later will be able to install this package without any configuration: they can just run `M-x list-packages` and install it out of the box. We hope that this will improve Emacs and help bring new users to this package and others. This commit adds installation instructions to README.md.
The main difference between NonGNU ELPA and MELPA is that only tagged versions of packages are released. This means that a new release will be automatically when you bump the "Version" commentary header in this repository. You can bump the package version (thereby releasing a new …

Add NonGNU ELPA instructions to README.md

---

README.md
gruvbox.el

Proof General sets some default colours which are not very nice on a dark BG (see screenshots).
This PR ensures that the colors are more consistent with the general gruvbox style

Better use of colors for Proof General

---

gruvbox.el

The `corfu-background` doesn't exist. See [corfu source code.](https://github.com/minad/corfu/blob/main/corfu.el) The `corfu-default` should be used instead.
Also, the proper background is inherited from `'tooltip`.
[REMOVED] `(corfu-background (:background gruvbox-dark1))`
[ADDED] `(corfu-default (:inherit 'tooltip))`
Dark:
Light (After):

Use corfu-default instead of corfu-background

---

gruvbox.el

isearch set to Black which in light themes will lead to poor contrast.

Fixes Issue #200 - Bad contrast

---

gruvbox.el

These two faces are used with font-lock to fontify different aspects of the buffers. In particular, if using the new treesit feature in Emacs 29, numbers on tree-sitter enabled buffers will appear blank.
Also, considering members use bright_purple, let's stick to bright_purple on properties too. It was defaulting to the built-in one, making the fontified buffer blue, while the idea is to highlight also the variable names blue, which would be the way that they are currently highlighted when declared.
For both changes, I added screenshots using the new tsx-ts-mode and [kotlin-ts-mode](https://gitlab.com/bricka/emacs-kotlin-ts-mode). What would change for numbers would be the numbers appearing white first, and then bright_purple. On the property change would be the members being blue moving …

Add font-lock-number and font-lock-property faces
