- gruvbox-theme.el
Thanks to JasonM23 I was able to add popup support using code from his Darktooth theme
I also changed some of the colors in popup-tip so let me know if that is an issue with anyone but I'm pretty happy with the results.
> Added popup support

- gruvbox-theme.el
> Make vertical border less harsh on the eyes

- gruvbox-theme.el
Adds an eval-when-compile to cl-lib for `cl-case`
> eval cl or cl-lib when compiling

- README.md
- gruvbox-theme.el
Just add a line for Anzu specific color, I used a bright yellow bold face because it's temporary addition to mode line.
> Add simple anzu mode specific configuration

- gruvbox.el
These faces were not defined and are occasionally used
> Added faces from the basic-faces group

- LICENSE
- gruvbox-light-hard-theme.el
- gruvbox-light-medium-theme.el
- gruvbox-light-soft-theme.el
- gruvbox.el
Using screenshots is quite useful when showing what faces look like in
a pull requests however can take more time to do by hand than changing
the actual faces so I automated it.
> Updated light theme under 256 color terminals

- gruvbox.el
New look:
Old look for reference
> Added missed faces for flyspell and customize

- gruvbox.el
> added faces for langtool

- gruvbox.el
> Added faces for LaTeX

- README.md
- gruvbox.el
> Added faces for ido-mode

- gruvbox-dark-hard-theme.el
- gruvbox-dark-medium-theme.el
- gruvbox-dark-soft-theme.el
- gruvbox-light-hard-theme.el
- gruvbox-light-medium-theme.el
- gruvbox-light-soft-theme.el
- gruvbox-theme.el
- gruvbox.el
I found a face I missed in https://github.com/greduan/emacs-theme-gruvbox/pull/97
old look:
new look:
> Added latex verbatim face

- README.md
- gruvbox-dark-hard-theme.el
- gruvbox-dark-medium-theme.el
- gruvbox-dark-soft-theme.el
- gruvbox-light-hard-theme.el
- gruvbox-light-medium-theme.el
- gruvbox-light-soft-theme.el
- gruvbox-theme.el
- gruvbox.el
Before (harsh colors/very ugly/odd color choices):
After (The new colors were chosen to resemble their role in dired mode):
> Added support for eshell

- gruvbox.el
> Use gruvbox-ligh0_hard for helm-action so it inverts correctly

- README.md
- gruvbox.el
> Add faces for diff-hl

- README.md
- gruvbox.el
> Add faces for Flycheck

- gruvbox.el
Minimal change to improve ediff readability
> improve readability in ediff

- gruvbox.el
> Fixed typo on aw-background-face foreground attrib

- LICENSE
My surname is slightly different now, and in full legal use in the UK. Therefore, I'd like to reflect it on the license here if it's not too much trouble.
> Reflect legal name change in license/copyright

- gruvbox.el
> Add faces for web-mode

- gruvbox.el
Hi there,
I added support for the following modes:
- [corfu.](https://github.com/minad/corfu)
- [marginalia.](https://github.com/minad/marginalia)
- [ledger-mode](https://github.com/ledger/ledger-mode).
Extensive descriptions have been provided in each of the commits. These are the changes that I use daily, and I find that they improve the experience on these modes a ton.
Most of the faces already have great inheritance support, but some of them clash with our gruvbox face setup. Adding the mentioned changes fixes the problems.
I will also comment below with images before and after the changes for each of the changes implemented.
I hope this pull request finds you well,
Best,
> Mode support: corfu, marginalia, ledger-mode

- gruvbox.el
Add support for helm-rg https://github.com/cosmicexplorer/helm-rg
> Add support for helm-rg

- gruvbox.el
- Added support for Avy as requested from issue #184
- updated previous support for Solaire (#186)
- removed background for minibuffer face to inherit parent background. (fixes Solaire issues)
Edit: Colours are very much up for debate, just matched them to the gruvbox colours
> Avy support + bug fixes

- gruvbox.el
refer to #184 - updated colours to be more visible and more Gruvbox.
> Updated Avy colours.

- gruvbox.el
> Add orderless

- gruvbox.el
Added a variable to allow for setting of bold constructs.
Added support for Elpaca Package manager.
fixes #201
> Variable to allow for bold constructs and Support for Elpaca

- README.md
- gruvbox-dark-hard-theme.el
- gruvbox-dark-medium-theme.el
- gruvbox-dark-soft-theme.el
- gruvbox-light-hard-theme.el
- gruvbox-light-medium-theme.el
- gruvbox-light-soft-theme.el
- gruvbox-theme.el
- gruvbox.el
This one's pretty self-explanatory :)
> Update urls and use SSL everywhere
